config/routes.rb
Rails.application.routes.draw do
  resources :microposts
  resources :users

  root 'nokogiri#index'
  
  get 'profile', to: 'users#new'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
    validates :content, length: { 
        maximum: 140,
        minimum: 5,
        too_short: "Minimal %{count} karakter",
        too_long: "Maksimal %{count} karakter"
    }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
    
    # Parse the URI and retrieve it to a temporary file
		news_tmp_file = open('http://tympanus.net/codrops/all-articles/page/1/')

		# Parse the contents of the temporary file as HTML
		doc = Nokogiri::HTML(news_tmp_file)

		# Define the css selectors to be used for extractions, most
		article_css_class         =".ct-archive-container"
		article_header_css_class  ="article.ct-box > h3 > a"
		article_image_css_class   ="//img[@class='attachment-thumbnail wp-post-image']/@src"
		article_summary_css_class =".ct-feat-excerpt"

		# extract all the articles 
		articles = doc.css(article_css_class)

		#html output
		title   = ""
		image   = ""
		summary = ""

		#extract the title from the articles
		articles.each do |article|
		  title    = article.search(article_header_css_class).map {|el| el.text}
		  image    = article.search(article_image_css_class).map {|a| a.value }
		  summary  = article.search(article_summary_css_class).map {|el| el.text}
		end
		
		# render :text => html,:content_type => "text/plain"
		@titles   = title
		@images   = image
		@summaries= summary
		
		@size = @titles.size
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render :show, status: :created, location: @micropost }
      else
        format.html { render :new }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { render :show, status: :ok, location: @micropost }
      else
        format.html { render :edit }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url, notice: 'Micropost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :user_id)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %>, Data tidak dapat disimpan:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, "Konten" %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing Micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<p id="notice"><%= notice %></p>

<!--<h1>Listing Microposts</h1>-->

<!--<table>-->
<!--  <thead>-->
<!--    <tr>-->
<!--      <th>Content</th>-->
<!--      <th>User</th>-->
<!--      <th colspan="3"></th>-->
<!--    </tr>-->
<!--  </thead>-->

<!--  <tbody>-->
<!--    <% @microposts.each do |micropost| %>-->
<!--      <tr>-->
<!--        <td><%= micropost.content %></td>-->
<!--        <td><%= micropost.user_id %></td>-->
<!--        <td><%= link_to 'Show', micropost %></td>-->
<!--        <td><%= link_to 'Edit', edit_micropost_path(micropost) %></td>-->
<!--        <td><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>-->
<!--      </tr>-->
<!--    <% end %>-->
<!--  </tbody>-->
<!--</table>-->

<!--<br>-->

<!--<%= link_to 'New Micropost', new_micropost_path %>-->


<% @titles.each do |title| %>
  <p><%= title %></p>
  <img src="
    <%= @images[9] %>"
  >
<% end %>
<hr/>
<% @summaries.each do |summary| %>
  <p><%= summary %></p>
<% end %>

app/views/microposts/new.html.erb
<h1>New Micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @micropost.content %>
</p>

<p>
  <strong>User:</strong>
  <%= @micropost.user_id %>
</p>

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>